CREATE TABLE addresses (
id INT PRIMARY KEY AUTO_INCREMENT,
street VARCHAR(300) NOT NULL,
house_number VARCHAR(300) NOT NULL,
city_id INT NOT NULL
);

CREATE TABLE users (
id INT PRIMARY KEY AUTO_INCREMENT,
first_name VARCHAR(300) NOT NULL,
last_name VARCHAR(300) NOT NULL,
email VARCHAR(200) NOT NULL,
address_id INT REFERENCES addresses (id) ON DELETE CASCADE
);

CREATE TABLE cities (
id INT PRIMARY KEY AUTO_INCREMENT,
city_name VARCHAR(100) UNIQUE NOT NULL
);
